base_url = "https://resume.applesauce.co.in"
compile_sass = true
title = "Shanur Rahman"
description = "A clean resume theme"
generate_feed = true
build_search_index = true
taxonomies = [
  { name = "tags", feed = true },
]

[markdown]
highlight_code = true
highlight_theme = "OneHalfLight"

[extra]
first_name = "Shanur"
last_name = "Rahman"
address = "New Delhi, India"
email = "shanur.cse.nitap@gmail.com"
favicon = "/favicon.ico"
avatar = "/media/avatar.png"

katex = false
show_about = true
show_skills = true
show_projects = false
show_opensource = true
show_publications = false
show_experience = true
show_education = true
show_blog = false
